version: "3.7"

services:
    database:
        image: mysql:8
        container_name: mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'password'
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            - '3306:3306'
        expose:
            - '3306'
    rabbitmq:
        image: rabbitmq:4.0-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672